version: '3'

services:
  web_spa_nextjs:
    container_name: web_spa_nextjs
    build: .
    command: sh -c "yarn --frozen-lockfile && yarn dev"
    environment:
      - "ES_CLIENT_URL=http://elastic:changeme@elasticsearch:9200"
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/instagram-feed/web-spa-nextjs
    depends_on:
      - elasticsearch
    links:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    image: docker.elastic.co/kibana/kibana:6.5.4
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml


volumes:
  esdata:
